#syntax
markdown: kramdown
highlighter: rouge
#dir and path 
#baseurl: /mylog
permalink: /:path
env : 'production'
# env : 'development'

exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"                  
  - "Rakefile"
  - "README.md"


#sass config
sass:
  sass_dir: assets/style
  style: compressed


#collections here
collections:

    postCollection: 
          output: true
          permalink: /posts/:path
    authors:
        output: true
        permalink: /about/:path

#plugins

plugins:
  - jekyll-seo-tag


#social and seo
name: initgrep
title: www.initgrep.com
description: Learn software development using initgrep tutorials - JavaScript, TypeScript, AngularJs, Java, Groovy, JPA, Spring, Spring Boot
logo: biglogo.jpg
image: biglogo.jpg 

twitter:
  username: initgrep

facebook:
  username: initgrep






